sonar.projectKey=Fraud-MLOps-Creditcard
sonar.projectName=Fraud MLOps Creditcard
sonar.projectVersion=1.0
sonar.sources=.
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=\
**/__pycache__/**,\
**/*.ipynb,\
venv/**,\
.env/**,\
model/model.pkl
sonar.python.coverage.reportPaths=coverage.xml
