name: Fraud MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  train-model:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Display Project Structure
      run: |
        pwd
        ls -R

    - name: Train LightGBM Model
      run: |
        python model/train.py

    - name: Verify Model
      run: |
        test -f model/model.pkl

    - name: Upload Trained Model
      uses: actions/upload-artifact@v4
      with:
        name: fraud-model
        path: model/model.pkl

    - name: Build Docker Image
      run: |
        docker build -t fraud-api:latest -f docker/Dockerfile .
