name: Fraud MLOps Creditcard

on:
  push:
    branches:
      - main

env:
  MODEL_PATH: model/model.pkl
  ACCURACY_THRESHOLD: 0.95

jobs:
  train-build-deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt

      - name: Check Existing Model
        id: model
        run: |
          if [ -f "$MODEL_PATH" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Train First Model
        if: steps.model.outputs.exists == 'false'
        run: |
          python model/train.py

      - name: Evaluate Existing Model
        if: steps.model.outputs.exists == 'true'
        id: evaluate
        continue-on-error: true
        run: |
          python model/evaluate.py

      - name: Retrain Because Accuracy Dropped
        if: steps.evaluate.outcome == 'failure'
        run: |
          python model/train.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login.outputs.registry }}
        run: |
          docker build -t $REGISTRY/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag $REGISTRY/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} \
                     $REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image
        env:
          REGISTRY: ${{ steps.login.outputs.registry }}
        run: |
          docker push $REGISTRY/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $REGISTRY/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER }}

      - name: Deploy
        run: |
          kubectl set image deployment/fraud-api \
            fraud-api=$REGISTRY/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

          kubectl rollout status deployment/fraud-api
